name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Get tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          draft: false
          prerelease: false

  build-android:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: ${{ needs.create-release.outputs.tag_name }}-android.apk
          asset_content_type: application/vnd.android.package-archive

  build-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      
      - name: Build
        run: flutter build windows --release
      
      - name: Install Inno Setup
        run: |
          choco install innosetup -y
      
      - name: Create Installer
        shell: pwsh
        run: |
          $buildPath = "build\windows\x64\Runner\Release"
          $appName = "Hello Flutter"
          $version = "${{ needs.create-release.outputs.tag_name }}"
          
          # Create Inno Setup script
          @"
          [Setup]
          AppName=$appName
          AppVersion=$version
          DefaultDirName={pf}\$appName
          DefaultGroupName=$appName
          OutputDir=.
          OutputBaseFilename=$appName-Setup
          
          [Files]
          Source: "$buildPath\*"; DestDir: "{app}"; Flags: recursesubdirs
          
          [Icons]
          Name: "{group}\$appName"; Filename: "{app}\hello_flutter.exe"
          Name: "{commondesktop}\$appName"; Filename: "{app}\hello_flutter.exe"
          "@ | Out-File -FilePath "installer.iss" -Encoding UTF8
          
          # Run Inno Setup Compiler
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installer.iss
      
      - name: Upload Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: Hello Flutter-Setup.exe
          asset_name: ${{ needs.create-release.outputs.tag_name }}-windows-setup.exe
          asset_content_type: application/vnd.microsoft.portable-executable
      
      - name: Create ZIP archive
        shell: pwsh
        run: |
          $buildPath = "build\windows\x64\Runner\Release"
          if (Test-Path $buildPath) {
            Compress-Archive -Path "$buildPath\*" -DestinationPath "windows-release.zip" -Force
          } else {
            Write-Error "Build path does not exist: $buildPath"
            exit 1
          }
      
      - name: Upload ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: windows-release.zip
          asset_name: ${{ needs.create-release.outputs.tag_name }}-windows-portable.zip
          asset_content_type: application/zip

  build-macos-ios:
    needs: create-release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      
      - name: Build macOS
        run: flutter build macos --release
      
      - name: Create DMG
        run: |
          brew install create-dmg
          APP_PATH="build/macos/Build/Products/Release/hello_flutter.app"
          DMG_PATH="Hello-Flutter.dmg"
          create-dmg \
            --volname "Hello Flutter" \
            --volicon "$APP_PATH/Contents/Resources/AppIcon.icns" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "$APP_PATH" 200 190 \
            --hide-extension "hello_flutter.app" \
            --app-drop-link 600 185 \
            "$DMG_PATH" \
            "$APP_PATH"
      
      - name: Upload DMG
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: Hello-Flutter.dmg
          asset_name: ${{ needs.create-release.outputs.tag_name }}-macos.dmg
          asset_content_type: application/x-apple-diskimage
      
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      
      - name: Create iOS Archive
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ios-app.ipa Payload
      
      - name: Upload iOS IPA
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: build/ios/iphoneos/ios-app.ipa
          asset_name: ${{ needs.create-release.outputs.tag_name }}-ios-unsigned.ipa
          asset_content_type: application/octet-stream

  build-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev cmake pkg-config libunwind-dev
          sudo apt-get install -y libwebkit2gtk-4.0-dev
          sudo apt-get install -y libsecret-1-dev libolm3
          sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          sudo apt-get install -y xvfb libxkbcommon-dev
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      
      - name: Build
        run: flutter build linux --release
      
      - name: Create ZIP archive
        run: |
          cd build/linux/x64/release/bundle
          zip -r ../../../../../linux-release.zip *
      
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: linux-release.zip
          asset_name: ${{ needs.create-release.outputs.tag_name }}-linux.zip
          asset_content_type: application/zip
